title: <p align="center"> Saket Bihari </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  Add resume File |
  LinkedIn Account link |
  Git Hub account link
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
